@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.winterhavenmc.savagegraveyards.models.searchkey.SearchKey",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1655488073 { 
   	label=winterhavenmc
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_718573502 { 
   	label=savagegraveyards
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   InvalidSearchKey1559188750[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)InvalidSearchKey</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   parameter: Parameter [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   reason: FailReason [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   string: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ parameter(): Parameter</TD></TR>
<TR><TD ALIGN="LEFT" >+ reason(): FailReason</TD></TR>
<TR><TD ALIGN="LEFT" >+ string(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SearchKey1559188750[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)SearchKey</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ isValid(): Optional&lt;ValidSearchKey&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ of(args: List&lt;String&gt;): SearchKey</TD></TR>
<TR><TD ALIGN="LEFT" >+ of(string: String): SearchKey</TD></TR>
<TR><TD ALIGN="LEFT" >+ string(): String</TD></TR>
<TR><TD ALIGN="LEFT" >- stripColor(string: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >- transform(string: String): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

ValidSearchKey1559188750[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ValidSearchKey</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   string: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ string(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
SearchKey1559188750 -> InvalidSearchKey1559188750[arrowhead=none, arrowtail=empty, dir=both];
SearchKey1559188750 -> ValidSearchKey1559188750[arrowhead=none, arrowtail=empty, dir=both];
    
}
@enduml