/*
 * Copyright (c) 2022-2025 Tim Savage.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package com.winterhavenmc.savagegraveyards.models;

/**
 * Enum with entries for all player messages in language configuration files
 */
public enum MessageId
{
	COMMAND_SUCCESS_CLOSEST,
	COMMAND_SUCCESS_CREATE,
	COMMAND_SUCCESS_CREATE_OVERWRITE,
	COMMAND_SUCCESS_DELETE,
	COMMAND_SUCCESS_FORGET,
	COMMAND_SUCCESS_RELOAD,

	COMMAND_SUCCESS_SET_NAME,
	COMMAND_SUCCESS_SET_LOCATION,
	COMMAND_SUCCESS_SET_ENABLED,
	COMMAND_SUCCESS_SET_HIDDEN,
	COMMAND_SUCCESS_SET_GROUP,
	COMMAND_SUCCESS_SET_DISCOVERY_MESSAGE,
	COMMAND_SUCCESS_SET_DISCOVERY_MESSAGE_DEFAULT,
	COMMAND_SUCCESS_SET_DISCOVERY_RANGE,
	COMMAND_SUCCESS_SET_DISCOVERY_RANGE_DEFAULT,
	COMMAND_SUCCESS_SET_RESPAWN_MESSAGE,
	COMMAND_SUCCESS_SET_RESPAWN_MESSAGE_DEFAULT,
	COMMAND_SUCCESS_SET_SAFETY_TIME,
	COMMAND_SUCCESS_SET_SAFETY_TIME_DEFAULT,

	COMMAND_FAIL_ARGS_COUNT_UNDER,
	COMMAND_FAIL_ARGS_COUNT_OVER,
	COMMAND_FAIL_CONSOLE,
	COMMAND_FAIL_CREATE_EXISTS,
	COMMAND_FAIL_CREATE_INSERT,
	COMMAND_FAIL_CREATE_INVALID,
	COMMAND_FAIL_CLOSEST_NO_MATCH,
	COMMAND_FAIL_DELETE_INVALID_KEY,
	COMMAND_FAIL_CREATE_INVALID_NAME,
	COMMAND_FAIL_FORGET,
	COMMAND_FAIL_FORGET_INVALID_GRAVEYARD,
	COMMAND_FAIL_FORGET_PLAYER_NOT_FOUND,
	COMMAND_FAIL_INVALID_ATTRIBUTE,
	COMMAND_FAIL_INVALID_COMMAND,
	COMMAND_FAIL_INVALID_HELP,

	COMMAND_FAIL_PERMISSION_CLOSEST,
	COMMAND_FAIL_PERMISSION_CREATE,
	COMMAND_FAIL_PERMISSION_DELETE,
	COMMAND_FAIL_PERMISSION_FORGET,
	COMMAND_FAIL_PERMISSION_HELP,
	COMMAND_FAIL_PERMISSION_LIST,
	COMMAND_FAIL_PERMISSION_RELOAD,
	COMMAND_FAIL_PERMISSION_SHOW,
	COMMAND_FAIL_PERMISSION_SET_LOCATION,
	COMMAND_FAIL_PERMISSION_SET_NAME,
	COMMAND_FAIL_PERMISSION_SET_ENABLED,
	COMMAND_FAIL_PERMISSION_SET_GROUP,
	COMMAND_FAIL_PERMISSION_SET_HIDDEN,
	COMMAND_FAIL_PERMISSION_SET_DISCOVERY_RANGE,
	COMMAND_FAIL_PERMISSION_SET_DISCOVERY_MESSAGE,
	COMMAND_FAIL_PERMISSION_SET_RESPAWN_MESSAGE,
	COMMAND_FAIL_PERMISSION_SET_SAFETY_TIME,
	COMMAND_FAIL_PERMISSION_STATUS,
	COMMAND_FAIL_PERMISSION_TELEPORT,

	COMMAND_FAIL_SET_INVALID_BOOLEAN,
	COMMAND_FAIL_SET_INVALID_INTEGER,
	COMMAND_FAIL_SET_INVALID_KEY,
	COMMAND_FAIL_SET_INVALID_NAME,
	COMMAND_FAIL_NO_RECORD,
	COMMAND_FAIL_TELEPORT,
	COMMAND_FAIL_TELEPORT_WORLD_INVALID,
	COMMAND_FAIL_TELEPORT_DESTINATION_KEY_INVALID,

	COMMAND_STATUS_HEADER,
	COMMAND_STATUS_ENABLED_WORLDS,
	COMMAND_STATUS_DISCOVERY_INTERVAL,
	COMMAND_STATUS_DISCOVERY_RANGE,
	COMMAND_STATUS_LANGUAGE,
	COMMAND_STATUS_LOCALE,
	COMMAND_STATUS_LOCALE_DETAIL,
	COMMAND_STATUS_LIST_SIZE,
	COMMAND_STATUS_PLUGIN_VERSION,
	COMMAND_STATUS_SAFETY_TIME,
	COMMAND_STATUS_SOUND_EFFECTS,
	COMMAND_STATUS_TIMEZONE,
	COMMAND_STATUS_FOOTER,

	COMMAND_DESCRIPTION_CLOSEST,
	COMMAND_DESCRIPTION_CREATE,
	COMMAND_DESCRIPTION_DELETE,
	COMMAND_DESCRIPTION_FORGET,
	COMMAND_DESCRIPTION_HELP,
	COMMAND_DESCRIPTION_LIST,
	COMMAND_DESCRIPTION_RELOAD,
	COMMAND_DESCRIPTION_SET,
	COMMAND_DESCRIPTION_SHOW,
	COMMAND_DESCRIPTION_STATUS,
	COMMAND_DESCRIPTION_TELEPORT,

	COMMAND_HELP_USAGE_HEADER,

	COMMAND_LIST_HEADER,
	COMMAND_LIST_FOOTER,
	COMMAND_LIST_ITEM,
	COMMAND_LIST_ITEM_DISABLED,
	COMMAND_LIST_ITEM_UNAVAILABLE,
	COMMAND_LIST_ITEM_UNDISCOVERED,
	COMMAND_LIST_ITEM_INVALID_WORLD,
	COMMAND_LIST_EMPTY,

	EVENT_DISCOVERY_DEFAULT,
	EVENT_RESPAWN_DEFAULT,
	EVENT_TELEPORT_SUCCESS_ARRIVAL,
	EVENT_TELEPORT_SUCCESS_DEPARTURE,

	SAFETY_COOLDOWN_START,
	SAFETY_COOLDOWN_END,
}
