@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 1,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "SqliteQueries; *Schema*",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.winterhavenmc.savagegraveyards.core.PluginController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1655488073 { 
   	label=winterhavenmc
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_718573502 { 
   	label=savagegraveyards
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   AbstractSubcommand578027687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AbstractSubcommand</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   aliases: Collection&lt;String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >#   description: MessageId [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   maxArgs: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   minArgs: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   permissionNode: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   usageString: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ displayUsage(sender: CommandSender)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onTabComplete(sender: CommandSender, command: Command, alias: String, args: String[]): List&lt;String&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Bootstrap520637518[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Bootstrap</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   commandManager: CommandManager [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   connectionProvider: ConnectionProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   discoveryObserver: DiscoveryObserver [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   playerEventListener: PlayerEventListener [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   pluginController: PluginController [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   safetyManager: SafetyManager [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onDisable()</TD></TR>
<TR><TD ALIGN="LEFT" >+ onEnable()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

BukkitCommandManager578027687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BukkitCommandManager</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ctx: CommandContextContainer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   subcommandRegistry: SubcommandRegistry [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- getSubcommandNameOrDefault(argsList: List&lt;String&gt;): String</TD></TR>
<TR><TD ALIGN="LEFT" >- getSubcommandOrFallback(sender: CommandSender, subcommandName: String): Optional&lt;Subcommand&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- hasPermission(sender: CommandSender): Predicate&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ init(ctx: CommandContextContainer): BukkitCommandManager</TD></TR>
<TR><TD ALIGN="LEFT" >- matchesPrefix(prefix: String): Predicate&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- matchingNames(sender: CommandSender, matchString: String): List&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- notifyInvalidCommand(sender: CommandSender, subcommandName: String): Optional&lt;Subcommand&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCommand(sender: CommandSender, command: Command, label: String, args: String[]): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ onTabComplete(sender: CommandSender, command: Command, alias: String, args: String[]): List&lt;String&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

BukkitPlayerEventListener395421368[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BukkitPlayerEventListener</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ctx: ListenerContextContainer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   deathTriggeredRespawn: Set&lt;UUID&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ init(ctx: ListenerContextContainer): BukkitPlayerEventListener</TD></TR>
<TR><TD ALIGN="LEFT" >+ onEntityTargetLivingEntity(event: EntityTargetLivingEntityEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onPlayerDeath(event: PlayerDeathEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onPlayerRespawnHIGH(event: PlayerRespawnEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onPlayerRespawnHIGHEST(event: PlayerRespawnEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >- onPlayerRespawnHandler(event: PlayerRespawnEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onPlayerRespawnLOW(event: PlayerRespawnEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onPlayerRespawnLOWEST(event: PlayerRespawnEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onPlayerRespawnNORMAL(event: PlayerRespawnEvent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ClosestSubcommand578027687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ClosestSubcommand</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ctx: CommandContextContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onCommand(sender: CommandSender, args: List&lt;String&gt;): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CommandContextContainer1340606838[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CommandContextContainer</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   discoveries: DiscoveryRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   discoveryObserver: DiscoveryObserver [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   graveyards: GraveyardRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   messageBuilder: MessageBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   plugin: JavaPlugin [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   soundConfig: SoundConfiguration [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   worldManager: WorldManager [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ discoveries(): DiscoveryRepository</TD></TR>
<TR><TD ALIGN="LEFT" >+ discoveryObserver(): DiscoveryObserver</TD></TR>
<TR><TD ALIGN="LEFT" >+ graveyards(): GraveyardRepository</TD></TR>
<TR><TD ALIGN="LEFT" >+ messageBuilder(): MessageBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ plugin(): JavaPlugin</TD></TR>
<TR><TD ALIGN="LEFT" >+ soundConfig(): SoundConfiguration</TD></TR>
<TR><TD ALIGN="LEFT" >+ worldManager(): WorldManager</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CreateSubcommand578027687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CreateSubcommand</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ctx: CommandContextContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- insertNewGraveyard(player: Player, displayName: ValidDisplayName): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCommand(sender: CommandSender, args: List&lt;String&gt;): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- overwriteExistingGraveyard(sender: CommandSender, graveyard: ValidGraveyard): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >- sendFailedInsertMessage(sender: CommandSender, graveyard: Graveyard): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >- sendFailedInvalidMessage(sender: CommandSender, graveyard: Graveyard): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >- sendInvalidNameMessage(sender: CommandSender, invalidName: InvalidDisplayName)</TD></TR>
<TR><TD ALIGN="LEFT" >- sendOverwriteDeniedMessage(sender: CommandSender, graveyard: Graveyard): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >- sendOverwriteSuccessMessage(sender: CommandSender, graveyard: ValidGraveyard): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >- sendSuccessMessage(sender: CommandSender, graveyard: Graveyard): Graveyard</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

DeleteSubcommand578027687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DeleteSubcommand</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ctx: CommandContextContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- invalidKeyMessage(sender: CommandSender, invalid: InvalidSearchKey)</TD></TR>
<TR><TD ALIGN="LEFT" >- notFoundMessage(sender: CommandSender, invalid: InvalidGraveyard)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCommand(sender: CommandSender, args: List&lt;String&gt;): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ onTabComplete(sender: CommandSender, command: Command, alias: String, args: String[]): List&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- successMessage(sender: CommandSender, graveyard: ValidGraveyard)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

DiscoveryContextContainer1340606838[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DiscoveryContextContainer</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   datastore: ConnectionProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   messageBuilder: MessageBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   plugin: Plugin [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   soundConfig: SoundConfiguration [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ datastore(): ConnectionProvider</TD></TR>
<TR><TD ALIGN="LEFT" >+ messageBuilder(): MessageBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ plugin(): Plugin</TD></TR>
<TR><TD ALIGN="LEFT" >+ soundConfig(): SoundConfiguration</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ForgetSubcommand578027687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ForgetSubcommand</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ctx: CommandContextContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- deleteDiscovery(sender: CommandSender, player: OfflinePlayer, searchKey: ValidSearchKey)</TD></TR>
<TR><TD ALIGN="LEFT" >- deleteFailed(sender: CommandSender)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCommand(sender: CommandSender, args: List&lt;String&gt;): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ onTabComplete(sender: CommandSender, command: Command, alias: String, args: String[]): List&lt;String&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

GraveyardDiscoveryObserver776919744[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)GraveyardDiscoveryObserver</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   datastore: ConnectionProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   discoveryTask: BukkitTask [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   messageBuilder: MessageBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   plugin: Plugin [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   soundConfig: SoundConfiguration [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ cancel()</TD></TR>
<TR><TD ALIGN="LEFT" >+ init(ctx: DiscoveryContextContainer): GraveyardDiscoveryObserver</TD></TR>
<TR><TD ALIGN="LEFT" >+ reload()</TD></TR>
<TR><TD ALIGN="LEFT" >+ run()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

HelpSubcommand578027687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)HelpSubcommand</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ctx: CommandContextContainer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   subcommandRegistry: SubcommandRegistry [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># displayUsageAll(sender: CommandSender)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCommand(sender: CommandSender, args: List&lt;String&gt;): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ onTabComplete(sender: CommandSender, command: Command, alias: String, args: String[]): List&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- sendCommandHelpMessage(sender: CommandSender, subcommand: Subcommand)</TD></TR>
<TR><TD ALIGN="LEFT" >- sendCommandInvalidMessage(sender: CommandSender)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListSubcommand578027687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListSubcommand</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ctx: CommandContextContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># allowInvalidIfPermitted(sender: CommandSender): Predicate&lt;Graveyard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" ># displayListFooter(sender: CommandSender, page: int, pageCount: int)</TD></TR>
<TR><TD ALIGN="LEFT" ># displayListHeader(sender: CommandSender, page: int, pageCount: int)</TD></TR>
<TR><TD ALIGN="LEFT" ># displayListItems(sender: CommandSender, displayRange: List&lt;Graveyard&gt;, itemNumber: int, undiscoveredKeys: Collection&lt;String&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" ># hasGroupPermission(sender: CommandSender): Predicate&lt;Graveyard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" ># isDiscoveredOrPermitted(sender: CommandSender, undiscovered: Set&lt;String&gt;): Predicate&lt;Graveyard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" ># isEnabledOrPermitted(sender: CommandSender): Predicate&lt;Graveyard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCommand(sender: CommandSender, args: List&lt;String&gt;): boolean</TD></TR>
<TR><TD ALIGN="LEFT" ># parsePage(string: String, max: int): int</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListenerContextContainer1340606838[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListenerContextContainer</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   graveyards: GraveyardRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   messageBuilder: MessageBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   plugin: JavaPlugin [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   safetyManager: SafetyManager [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   worldManager: WorldManager [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ graveyards(): GraveyardRepository</TD></TR>
<TR><TD ALIGN="LEFT" >+ messageBuilder(): MessageBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ plugin(): JavaPlugin</TD></TR>
<TR><TD ALIGN="LEFT" >+ safetyManager(): SafetyManager</TD></TR>
<TR><TD ALIGN="LEFT" >+ worldManager(): WorldManager</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PluginController1876166622[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)PluginController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ shutDown()</TD></TR>
<TR><TD ALIGN="LEFT" >+ startUp(plugin: JavaPlugin, connectionProvider: ConnectionProvider, commandManager: CommandManager, playerEventListener: PlayerEventListener, discoveryObserver: DiscoveryObserver, safetyManager: SafetyManager)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

ReloadSubcommand578027687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ReloadSubcommand</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ctx: CommandContextContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onCommand(sender: CommandSender, args: List&lt;String&gt;): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

RespawnSafetyManager1159211330[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)RespawnSafetyManager</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   messageBuilder: MessageBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   plugin: Plugin [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   safetyCooldownMap: Map&lt;UUID, BukkitRunnable&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ init(ctx: SafetyContextContainer): RespawnSafetyManager</TD></TR>
<TR><TD ALIGN="LEFT" >+ isProtected(player: Player): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ put(player: Player, graveyard: ValidGraveyard)</TD></TR>
<TR><TD ALIGN="LEFT" >+ remove(player: Player)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SavageGraveyardsPluginController1876166622[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SavageGraveyardsPluginController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   commandManager: CommandManager [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   datastore: ConnectionProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   discoveryObserver: DiscoveryObserver [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   messageBuilder: MessageBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   playerEventListener: PlayerEventListener [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   safetyManager: SafetyManager [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   soundConfig: SoundConfiguration [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   worldManager: WorldManager [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ shutDown()</TD></TR>
<TR><TD ALIGN="LEFT" >+ startUp(plugin: JavaPlugin, connectionProvider: ConnectionProvider, commandManager: CommandManager, playerEventListener: PlayerEventListener, discoveryObserver: DiscoveryObserver, safetyManager: SafetyManager)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SetSubcommand578027687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SetSubcommand</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ctx: CommandContextContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- matchPermittedAttributes(sender: CommandSender, partialMatch: String): List&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCommand(sender: CommandSender, args: List&lt;String&gt;): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ onTabComplete(sender: CommandSender, command: Command, alias: String, args: String[]): List&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- sendFailInvalidKey(sender: CommandSender, invalidKey: InvalidSearchKey)</TD></TR>
<TR><TD ALIGN="LEFT" >- sendFailNoMatch(sender: CommandSender, graveyard: Graveyard): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- sendFailSelect(sender: CommandSender, graveyard: Graveyard)</TD></TR>
<TR><TD ALIGN="LEFT" >- setDiscoveryMessage(sender: CommandSender, graveyard: ValidGraveyard, passedString: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- setDiscoveryRange(sender: CommandSender, graveyard: ValidGraveyard, passedString: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- setEnabled(sender: CommandSender, graveyard: ValidGraveyard, passedString: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- setGroup(sender: CommandSender, graveyard: ValidGraveyard, passedString: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- setHidden(sender: CommandSender, graveyard: ValidGraveyard, passedString: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" ># setLocation(sender: CommandSender, graveyard: ValidGraveyard): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- setName(sender: CommandSender, originalGraveyard: ValidGraveyard, passedString: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- setRespawnMessage(sender: CommandSender, graveyard: ValidGraveyard, passedString: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- setSafetyTime(sender: CommandSender, graveyard: ValidGraveyard, passedString: String): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ShowSubcommand578027687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ShowSubcommand</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ctx: CommandContextContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onCommand(sender: CommandSender, args: List&lt;String&gt;): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ onTabComplete(sender: CommandSender, command: Command, alias: String, args: String[]): List&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- sendNotFoundMessage(sender: CommandSender, searchKey: SearchKey)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SqliteConnectionProvider1287084334[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SqliteConnectionProvider</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   connection: Connection [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dataFilePath: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   discoveryRepository: SqliteDiscoveryRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   graveyardRepository: SqliteGraveyardRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   initialized: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   localeProvider: LocaleProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   plugin: Plugin [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ close()</TD></TR>
<TR><TD ALIGN="LEFT" >+ connect(): ConnectionProvider</TD></TR>
<TR><TD ALIGN="LEFT" >- createDiscoveryTable(connection: Connection, localeProvider: LocaleProvider)</TD></TR>
<TR><TD ALIGN="LEFT" >- createGraveyardTable(connection: Connection, localeProvider: LocaleProvider)</TD></TR>
<TR><TD ALIGN="LEFT" >+ discoveries(): DiscoveryRepository</TD></TR>
<TR><TD ALIGN="LEFT" >- enableForeignKeys(connection: Connection, localeProvider: LocaleProvider)</TD></TR>
<TR><TD ALIGN="LEFT" >+ graveyards(): GraveyardRepository</TD></TR>
<TR><TD ALIGN="LEFT" >- initialize()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SqliteGraveyardRepository1287084334[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SqliteGraveyardRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   connection: Connection [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   graveyardMapper: SqliteGraveyardRowMapper [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   localeProvider: LocaleProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   logger: Logger [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   queryExecutor: SqliteGraveyardQueryExecutor [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ delete(searchKey: ValidSearchKey): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >+ get(searchKey: ValidSearchKey): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >+ getMatchingKeys(prefix: String): List&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getMatchingNames(prefix: String): List&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getNearestGraveyard(player: Player): Optional&lt;ValidGraveyard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getNearestGraveyards(player: Player): List&lt;ValidGraveyard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getUndiscoveredGraveyards(player: Player): Stream&lt;ValidGraveyard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getUndiscoveredKeys(sender: CommandSender): Set&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ save(graveyard: ValidGraveyard): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >+ saveAll(graveyards: Collection&lt;ValidGraveyard&gt;): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ update(graveyard: ValidGraveyard): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >+ update(oldSearchKey: ValidSearchKey, graveyard: ValidGraveyard): Graveyard</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

StatusSubcommand578027687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)StatusSubcommand</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ctx: CommandContextContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- displayDebug(sender: CommandSender)</TD></TR>
<TR><TD ALIGN="LEFT" >- displayDiscoveryInterval(sender: CommandSender)</TD></TR>
<TR><TD ALIGN="LEFT" >- displayDiscoveryRange(sender: CommandSender)</TD></TR>
<TR><TD ALIGN="LEFT" >- displayEnabledWorlds(sender: CommandSender)</TD></TR>
<TR><TD ALIGN="LEFT" >- displayLanguage(sender: CommandSender)</TD></TR>
<TR><TD ALIGN="LEFT" >- displayListItemPageSize(sender: CommandSender)</TD></TR>
<TR><TD ALIGN="LEFT" >- displayLocale(sender: CommandSender)</TD></TR>
<TR><TD ALIGN="LEFT" >- displayPluginVersion(sender: CommandSender)</TD></TR>
<TR><TD ALIGN="LEFT" >- displaySafetyTime(sender: CommandSender)</TD></TR>
<TR><TD ALIGN="LEFT" >- displayStatusBanner(sender: CommandSender)</TD></TR>
<TR><TD ALIGN="LEFT" >- displayStatusFooter(sender: CommandSender)</TD></TR>
<TR><TD ALIGN="LEFT" >- displayTimezone(sender: CommandSender)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCommand(sender: CommandSender, args: List&lt;String&gt;): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SubcommandRegistry578027687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SubcommandRegistry</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   aliasMap: Map&lt;String, String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >#   subcommandMap: Map&lt;String, Subcommand&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># getSubcommand(name: String): Optional&lt;Subcommand&gt;</TD></TR>
<TR><TD ALIGN="LEFT" ># register(subcommand: Subcommand)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TeleportCommand578027687[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TeleportCommand</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ctx: CommandContextContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onCommand(sender: CommandSender, args: List&lt;String&gt;): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ onTabComplete(sender: CommandSender, command: Command, alias: String, args: String[]): List&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- sendKeyInvalidMessage(sender: CommandSender, invalid: InvalidSearchKey)</TD></TR>
<TR><TD ALIGN="LEFT" >- teleportFail(sender: CommandSender, graveyard: Graveyard)</TD></TR>
<TR><TD ALIGN="LEFT" >- teleportPlayer(player: Player, graveyard: ValidGraveyard)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ValidGraveyard46012934[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ValidGraveyard</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   attributes: Attributes [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   displayName: ValidDisplayName [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   location: ValidLocation [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ attributes(): Attributes</TD></TR>
<TR><TD ALIGN="LEFT" >+ displayName(): ValidDisplayName</TD></TR>
<TR><TD ALIGN="LEFT" >+ location(): ValidLocation</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchKey(): ValidSearchKey</TD></TR>
<TR><TD ALIGN="LEFT" >+ worldName(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Bootstrap520637518 -> PluginController1876166622[label="pluginController
[0..1]"];
BukkitCommandManager578027687 -> AbstractSubcommand578027687[arrowhead=none];
BukkitCommandManager578027687 -> ClosestSubcommand578027687[arrowhead=none];
BukkitCommandManager578027687 -> CommandContextContainer1340606838[label="ctx
[0..1]"];
BukkitCommandManager578027687 -> CreateSubcommand578027687[arrowhead=none];
BukkitCommandManager578027687 -> DeleteSubcommand578027687[arrowhead=none];
BukkitCommandManager578027687 -> ForgetSubcommand578027687[arrowhead=none];
BukkitCommandManager578027687 -> HelpSubcommand578027687[arrowhead=none];
BukkitCommandManager578027687 -> ListSubcommand578027687[arrowhead=none];
BukkitCommandManager578027687 -> ReloadSubcommand578027687[arrowhead=none];
BukkitCommandManager578027687 -> SetSubcommand578027687[arrowhead=none];
BukkitCommandManager578027687 -> ShowSubcommand578027687[arrowhead=none];
BukkitCommandManager578027687 -> StatusSubcommand578027687[arrowhead=none];
BukkitCommandManager578027687 -> SubcommandRegistry578027687[label="subcommandRegistry
[0..1]"];
BukkitCommandManager578027687 -> TeleportCommand578027687[arrowhead=none];
BukkitPlayerEventListener395421368 -> ListenerContextContainer1340606838[label="ctx
[0..1]"];
BukkitPlayerEventListener395421368 -> RespawnSafetyManager1159211330[arrowhead=none];
BukkitPlayerEventListener395421368 -> SqliteGraveyardRepository1287084334[arrowhead=none];
BukkitPlayerEventListener395421368 -> ValidGraveyard46012934[label="onPlayerRespawnHandler() -> displayName()"];
GraveyardDiscoveryObserver776919744 -> SqliteConnectionProvider1287084334[arrowhead=none];
PluginController1876166622 -> SavageGraveyardsPluginController1876166622[arrowhead=none, arrowtail=empty, dir=both];
SavageGraveyardsPluginController1876166622 -> BukkitCommandManager578027687[arrowhead=none];
SavageGraveyardsPluginController1876166622 -> BukkitPlayerEventListener395421368[arrowhead=none];
SavageGraveyardsPluginController1876166622 -> GraveyardDiscoveryObserver776919744[arrowhead=none];
    
}
@enduml