@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.winterhavenmc.savagegraveyards.core.SavageGraveyardsPluginController#startUp(JavaPlugin,ConnectionProvider,CommandManager,PlayerEventListener,DiscoveryObserver,SafetyManager)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 4,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.winterhavenmc.savagegraveyards.core.SavageGraveyardsPluginController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1655488073 { 
   	label=winterhavenmc
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_718573502 { 
   	label=savagegraveyards
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1081048705 { 
   	label=RespawnSafetyManager
	labeljust=l
	fillcolor=white
	style=filled
   
   RespawnSafetyManager1159211330XXXinit1162431867[
	label="+ init()"
	style=filled
	fillcolor=white
	tooltip="RespawnSafetyManager

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_120757199 { 
   	label=SqliteSchemaUpdaterNoOp
	labeljust=l
	fillcolor=white
	style=filled
   
   SqliteSchemaUpdaterNoOp2051509663XXXupdate0[
	label="+ update()"
	style=filled
	fillcolor=white
	tooltip="SqliteSchemaUpdaterNoOp

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1226219125 { 
   	label=BukkitCommandManager
	labeljust=l
	fillcolor=white
	style=filled
   
   BukkitCommandManager578027687XXXinit1491521315[
	label="+ init()"
	style=filled
	fillcolor=white
	tooltip="BukkitCommandManager

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1253292838 { 
   	label=SqliteQueries
	labeljust=l
	fillcolor=white
	style=filled
   
   SqliteQueries1287084334XXXgetQuery1808118735[
	label="+ getQuery()"
	style=filled
	fillcolor=white
	tooltip="SqliteQueries

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1340606838 { 
   	label=SavageGraveyardsPluginController
	labeljust=l
	fillcolor=white
	style=filled
   
   SavageGraveyardsPluginController1876166622XXXstartUp489187328[
	label="+ startUp()"
	style=filled
	fillcolor=white
	tooltip="SavageGraveyardsPluginController

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_1375568110 { 
   	label=Bootstrap
	labeljust=l
	fillcolor=white
	style=filled
   
   Bootstrap520637518XXXonEnable0[
	label="+ onEnable()"
	style=filled
	fillcolor=white
	tooltip="Bootstrap

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_2078381358 { 
   	label=PlayerEventListener
	labeljust=l
	fillcolor=white
	style=filled
   
   PlayerEventListener642410157XXXinit1577881466[
	label="+ init()"
	style=filled
	fillcolor=white
	tooltip="PlayerEventListener

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_308860749 { 
   	label=SqliteSchemaUpdaterFromV0
	labeljust=l
	fillcolor=white
	style=filled
   
   SqliteSchemaUpdaterFromV02051509663XXXupdate0[
	label="+ update()"
	style=filled
	fillcolor=white
	tooltip="SqliteSchemaUpdaterFromV0

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_31350265 { 
   	label=BukkitPlayerEventListener
	labeljust=l
	fillcolor=white
	style=filled
   
   BukkitPlayerEventListener395421368XXXinit1577881466[
	label="+ init()"
	style=filled
	fillcolor=white
	tooltip="BukkitPlayerEventListener

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_336641739 { 
   	label=GraveyardDiscoveryObserver
	labeljust=l
	fillcolor=white
	style=filled
   
   GraveyardDiscoveryObserver776919744XXXinit66954439[
	label="+ init()"
	style=filled
	fillcolor=white
	tooltip="GraveyardDiscoveryObserver

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_40209659 { 
   	label=SqliteConnectionProvider
	labeljust=l
	fillcolor=white
	style=filled
   
   SqliteConnectionProvider1287084334XXXconnect0[
	label="+ connect()"
	style=filled
	fillcolor=white
	tooltip="SqliteConnectionProvider

&#10;	  Initialize datastore&#10;	 "
	fontcolor=darkgreen
];

SqliteConnectionProvider1287084334XXXdiscoveries0[
	label="+ discoveries()"
	style=filled
	fillcolor=white
	tooltip="SqliteConnectionProvider

&#10;	  Get instance of DiscoveryRepository&#10;	 &#10;	  @return {@link DiscoveryRepository}&#10;	 "
	fontcolor=darkgreen
];

SqliteConnectionProvider1287084334XXXgraveyards0[
	label="+ graveyards()"
	style=filled
	fillcolor=white
	tooltip="SqliteConnectionProvider

&#10;	  Get instance of GraveyardRepository&#10;	 &#10;	  @return {@link GraveyardRepository}&#10;	 "
	fontcolor=darkgreen
];
} 

subgraph cluster_582128466 { 
   	label=ConnectionProvider
	labeljust=l
	fillcolor=white
	style=filled
   
   ConnectionProvider231410315XXXconnect0[
	label="+ connect()"
	style=filled
	fillcolor=white
	tooltip="ConnectionProvider

&#10;	  Initialize datastore&#10;	 "
	fontcolor=darkgreen
];

ConnectionProvider231410315XXXdiscoveries0[
	label="+ discoveries()"
	style=filled
	fillcolor=white
	tooltip="ConnectionProvider

&#10;	  Get instance of DiscoveryRepository&#10;	 &#10;	  @return {@link DiscoveryRepository}&#10;	 "
	fontcolor=darkgreen
];

ConnectionProvider231410315XXXgraveyards0[
	label="+ graveyards()"
	style=filled
	fillcolor=white
	tooltip="ConnectionProvider

&#10;	  Get instance of GraveyardRepository&#10;	 &#10;	  @return {@link GraveyardRepository}&#10;	 "
	fontcolor=darkgreen
];
} 

subgraph cluster_683359400 { 
   	label=DiscoveryObserver
	labeljust=l
	fillcolor=white
	style=filled
   
   DiscoveryObserver776919744XXXinit66954439[
	label="+ init()"
	style=filled
	fillcolor=white
	tooltip="DiscoveryObserver

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_740776508 { 
   	label=CommandManager
	labeljust=l
	fillcolor=white
	style=filled
   
   CommandManager1969417996XXXinit1491521315[
	label="+ init()"
	style=filled
	fillcolor=white
	tooltip="CommandManager

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_803066031 { 
   	label=SafetyManager
	labeljust=l
	fillcolor=white
	style=filled
   
   SafetyManager1159211330XXXinit1162431867[
	label="+ init()"
	style=filled
	fillcolor=white
	tooltip="SafetyManager

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_82861217 { 
   	label=PluginController
	labeljust=l
	fillcolor=white
	style=filled
   
   PluginController1876166622XXXstartUp489187328[
	label="+ startUp()"
	style=filled
	fillcolor=white
	tooltip="PluginController

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_840506353 { 
   	label=SqliteSchemaUpdater
	labeljust=l
	fillcolor=white
	style=filled
   
   SqliteSchemaUpdater2051509663XXXcreate166494955[
	label="+ create()"
	style=filled
	fillcolor=white
	tooltip="SqliteSchemaUpdater

null"
	fontcolor=darkgreen
];

SqliteSchemaUpdater2051509663XXXgetSchemaVersion627813921[
	label="+ getSchemaVersion()"
	style=filled
	fillcolor=white
	tooltip="SqliteSchemaUpdater

null"
	fontcolor=darkgreen
];

SqliteSchemaUpdater2051509663XXXupdate0[
	label="+ update()"
	style=filled
	fillcolor=white
	tooltip="SqliteSchemaUpdater

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
Bootstrap520637518XXXonEnable0 -> PluginController1876166622XXXstartUp489187328;
CommandManager1969417996XXXinit1491521315 -> BukkitCommandManager578027687XXXinit1491521315;
ConnectionProvider231410315XXXconnect0 -> SqliteConnectionProvider1287084334XXXconnect0;
ConnectionProvider231410315XXXdiscoveries0 -> SqliteConnectionProvider1287084334XXXdiscoveries0;
ConnectionProvider231410315XXXgraveyards0 -> SqliteConnectionProvider1287084334XXXgraveyards0;
DiscoveryObserver776919744XXXinit66954439 -> GraveyardDiscoveryObserver776919744XXXinit66954439;
PlayerEventListener642410157XXXinit1577881466 -> BukkitPlayerEventListener395421368XXXinit1577881466;
PluginController1876166622XXXstartUp489187328 -> SavageGraveyardsPluginController1876166622XXXstartUp489187328;
SafetyManager1159211330XXXinit1162431867 -> RespawnSafetyManager1159211330XXXinit1162431867;
SavageGraveyardsPluginController1876166622XXXstartUp489187328 -> CommandManager1969417996XXXinit1491521315;
SavageGraveyardsPluginController1876166622XXXstartUp489187328 -> ConnectionProvider231410315XXXconnect0;
SavageGraveyardsPluginController1876166622XXXstartUp489187328 -> ConnectionProvider231410315XXXdiscoveries0;
SavageGraveyardsPluginController1876166622XXXstartUp489187328 -> ConnectionProvider231410315XXXgraveyards0;
SavageGraveyardsPluginController1876166622XXXstartUp489187328 -> DiscoveryObserver776919744XXXinit66954439;
SavageGraveyardsPluginController1876166622XXXstartUp489187328 -> PlayerEventListener642410157XXXinit1577881466;
SavageGraveyardsPluginController1876166622XXXstartUp489187328 -> SafetyManager1159211330XXXinit1162431867;
SqliteConnectionProvider1287084334XXXconnect0 -> SqliteQueries1287084334XXXgetQuery1808118735;
SqliteConnectionProvider1287084334XXXconnect0 -> SqliteSchemaUpdater2051509663XXXcreate166494955;
SqliteConnectionProvider1287084334XXXconnect0 -> SqliteSchemaUpdater2051509663XXXupdate0;
SqliteSchemaUpdater2051509663XXXcreate166494955 -> SqliteSchemaUpdater2051509663XXXgetSchemaVersion627813921;
SqliteSchemaUpdater2051509663XXXupdate0 -> SqliteSchemaUpdaterFromV02051509663XXXupdate0;
SqliteSchemaUpdater2051509663XXXupdate0 -> SqliteSchemaUpdaterNoOp2051509663XXXupdate0;
    
}
@enduml