@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.winterhavenmc.savagegraveyards.core.SavageGraveyardsPluginController#shutDown()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 4,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.winterhavenmc.savagegraveyards.core.SavageGraveyardsPluginController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1655488073 { 
   	label=winterhavenmc
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_718573502 { 
   	label=savagegraveyards
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1340606838 { 
   	label=SavageGraveyardsPluginController
	labeljust=l
	fillcolor=white
	style=filled
   
   SavageGraveyardsPluginController1876166622XXXshutDown0[
	label="+ shutDown()"
	style=filled
	fillcolor=white
	tooltip="SavageGraveyardsPluginController

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_1375568110 { 
   	label=Bootstrap
	labeljust=l
	fillcolor=white
	style=filled
   
   Bootstrap520637518XXXonDisable0[
	label="+ onDisable()"
	style=filled
	fillcolor=white
	tooltip="Bootstrap

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_336641739 { 
   	label=GraveyardDiscoveryObserver
	labeljust=l
	fillcolor=white
	style=filled
   
   GraveyardDiscoveryObserver776919744XXXcancel0[
	label="+ cancel()"
	style=filled
	fillcolor=white
	tooltip="GraveyardDiscoveryObserver

&#10;	  Cancel a running DiscoveryTask&#10;	 "
	fontcolor=darkgreen
];
} 

subgraph cluster_40209659 { 
   	label=SqliteConnectionProvider
	labeljust=l
	fillcolor=white
	style=filled
   
   SqliteConnectionProvider1287084334XXXclose0[
	label="+ close()"
	style=filled
	fillcolor=white
	tooltip="SqliteConnectionProvider

&#10;	  Close SQLite datastore connection&#10;	 "
	fontcolor=darkgreen
];
} 

subgraph cluster_582128466 { 
   	label=ConnectionProvider
	labeljust=l
	fillcolor=white
	style=filled
   
   ConnectionProvider231410315XXXclose0[
	label="+ close()"
	style=filled
	fillcolor=white
	tooltip="ConnectionProvider

&#10;	  Close SQLite datastore connection&#10;	 "
	fontcolor=darkgreen
];
} 

subgraph cluster_683359400 { 
   	label=DiscoveryObserver
	labeljust=l
	fillcolor=white
	style=filled
   
   DiscoveryObserver776919744XXXcancel0[
	label="+ cancel()"
	style=filled
	fillcolor=white
	tooltip="DiscoveryObserver

&#10;	  Cancel a running DiscoveryTask&#10;	 "
	fontcolor=darkgreen
];
} 

subgraph cluster_82861217 { 
   	label=PluginController
	labeljust=l
	fillcolor=white
	style=filled
   
   PluginController1876166622XXXshutDown0[
	label="+ shutDown()"
	style=filled
	fillcolor=white
	tooltip="PluginController

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
Bootstrap520637518XXXonDisable0 -> PluginController1876166622XXXshutDown0;
ConnectionProvider231410315XXXclose0 -> SqliteConnectionProvider1287084334XXXclose0;
DiscoveryObserver776919744XXXcancel0 -> GraveyardDiscoveryObserver776919744XXXcancel0;
PluginController1876166622XXXshutDown0 -> SavageGraveyardsPluginController1876166622XXXshutDown0;
SavageGraveyardsPluginController1876166622XXXshutDown0 -> ConnectionProvider231410315XXXclose0;
SavageGraveyardsPluginController1876166622XXXshutDown0 -> DiscoveryObserver776919744XXXcancel0;
    
}
@enduml