@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "*attributes*",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "*Subcommand; *Key",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 5,
    "backwardDepth": 0,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.winterhavenmc.savagegraveyards.core.listeners.PlayerEventListener",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1655488073 { 
   	label=winterhavenmc
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_718573502 { 
   	label=savagegraveyards
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   AvailableWorld1429396403[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AvailableWorld</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   uid: UUID [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ uid(): UUID</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

InvalidDiscovery836352235[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)InvalidDiscovery</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   discoveryFailReason: DiscoveryFailReason [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ discoveryFailReason(): DiscoveryFailReason</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

InvalidDisplayName1488080184[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)InvalidDisplayName</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   reason: DisplayNameFailReason [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   string: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ reason(): DisplayNameFailReason</TD></TR>
<TR><TD ALIGN="LEFT" >+ string(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

InvalidGraveyard46012934[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)InvalidGraveyard</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   displayName: DisplayName [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   graveyardFailReason: GraveyardFailReason [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   worldName: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ displayName(): DisplayName</TD></TR>
<TR><TD ALIGN="LEFT" >+ graveyardFailReason(): GraveyardFailReason</TD></TR>
<TR><TD ALIGN="LEFT" >+ worldName(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

InvalidLocation977561318[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)InvalidLocation</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   reason: LocationFailReason [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ reason(): LocationFailReason</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

InvalidSearchKey1559188750[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)InvalidSearchKey</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   reason: SearchKeyFailReason [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   string: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ reason(): SearchKeyFailReason</TD></TR>
<TR><TD ALIGN="LEFT" >+ string(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

InvalidWorld1429396403[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)InvalidWorld</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   reason: WorldFailReason [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ reason(): WorldFailReason</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListenerContextContainer82861217[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListenerContextContainer</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   datastore: ConnectionProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   messageBuilder: MessageBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   plugin: JavaPlugin [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   safetyManager: SafetyManager [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   worldManager: WorldManager [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ datastore(): ConnectionProvider</TD></TR>
<TR><TD ALIGN="LEFT" >+ messageBuilder(): MessageBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ plugin(): JavaPlugin</TD></TR>
<TR><TD ALIGN="LEFT" >+ safetyManager(): SafetyManager</TD></TR>
<TR><TD ALIGN="LEFT" >+ worldManager(): WorldManager</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PlayerEventListener1298632657[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PlayerEventListener</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ctx: ListenerContextContainer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   deathTriggeredRespawn: Set&lt;UUID&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># onEntityTargetLivingEntity(event: EntityTargetLivingEntityEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onPlayerDeath(event: PlayerDeathEvent)</TD></TR>
<TR><TD ALIGN="LEFT" ># onPlayerRespawnHIGH(event: PlayerRespawnEvent)</TD></TR>
<TR><TD ALIGN="LEFT" ># onPlayerRespawnHIGHEST(event: PlayerRespawnEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >- onPlayerRespawnHandler(event: PlayerRespawnEvent)</TD></TR>
<TR><TD ALIGN="LEFT" ># onPlayerRespawnLOW(event: PlayerRespawnEvent)</TD></TR>
<TR><TD ALIGN="LEFT" ># onPlayerRespawnLOWEST(event: PlayerRespawnEvent)</TD></TR>
<TR><TD ALIGN="LEFT" ># onPlayerRespawnNORMAL(event: PlayerRespawnEvent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SafetyManager1054240386[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SafetyManager</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   messageBuilder: MessageBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   plugin: Plugin [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   safetyCooldownMap: Map&lt;UUID, BukkitRunnable&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ isProtected(player: Player): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ put(player: Player, graveyard: ValidGraveyard)</TD></TR>
<TR><TD ALIGN="LEFT" >+ remove(player: Player)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SqliteConnectionProvider1287084334[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SqliteConnectionProvider</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   connection: Connection [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dataFilePath: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   discoveryRepository: SqliteDiscoveryRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   graveyardRepository: SqliteGraveyardRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   initialized: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   localeProvider: LocaleProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   plugin: Plugin [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ close()</TD></TR>
<TR><TD ALIGN="LEFT" >+ connect(): ConnectionProvider</TD></TR>
<TR><TD ALIGN="LEFT" >- createDiscoveryTable(connection: Connection, localeProvider: LocaleProvider)</TD></TR>
<TR><TD ALIGN="LEFT" >- createGraveyardTable(connection: Connection, localeProvider: LocaleProvider)</TD></TR>
<TR><TD ALIGN="LEFT" >+ discoveries(): DiscoveryRepository</TD></TR>
<TR><TD ALIGN="LEFT" >- enableForeignKeys(connection: Connection, localeProvider: LocaleProvider)</TD></TR>
<TR><TD ALIGN="LEFT" >+ graveyards(): GraveyardRepository</TD></TR>
<TR><TD ALIGN="LEFT" >- initialize()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SqliteDiscoveryQueryExecutor1287084334[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SqliteDiscoveryQueryExecutor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ deleteDiscovery(searchKey: SearchKey, playerUid: UUID, preparedStatement: PreparedStatement): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ insertDiscovery(validDiscovery: ValidDiscovery, preparedStatement: PreparedStatement): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ selectAllDiscoveries(preparedStatement: PreparedStatement): ResultSet</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SqliteDiscoveryRepository1287084334[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SqliteDiscoveryRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   connection: Connection [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   discoveryMapper: SqliteDiscoveryRowMapper [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   localeProvider: LocaleProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   logger: Logger [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   queryExecutor: SqliteDiscoveryQueryExecutor [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ delete(searchKey: ValidSearchKey, playerUid: UUID): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ save(discovery: ValidDiscovery): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ saveAll(discoveries: Collection&lt;ValidDiscovery&gt;): int</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SqliteDiscoveryRowMapper1287084334[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SqliteDiscoveryRowMapper</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ map(resultSet: ResultSet): Discovery</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SqliteGraveyardQueryExecutor1287084334[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SqliteGraveyardQueryExecutor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ SelectNearestGraveyards(player: Player, preparedStatement: PreparedStatement): ResultSet</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteGraveyard(searchKey: ValidSearchKey, preparedStatement: PreparedStatement): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ insertGraveyard(graveyard: ValidGraveyard, preparedStatement: PreparedStatement): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ selectMatchingGraveyardKeys(prefix: String, preparedStatement: PreparedStatement): ResultSet</TD></TR>
<TR><TD ALIGN="LEFT" >+ selectMatchingGraveyardNames(prefix: String, preparedStatement: PreparedStatement): ResultSet</TD></TR>
<TR><TD ALIGN="LEFT" >+ selectNearestGraveyard(player: Player, preparedStatement: PreparedStatement): ResultSet</TD></TR>
<TR><TD ALIGN="LEFT" >+ selectUndiscoveredGraveyards(player: Player, preparedStatement: PreparedStatement): ResultSet</TD></TR>
<TR><TD ALIGN="LEFT" >+ selectUndiscoveredKeys(player: Player, preparedStatement: PreparedStatement): ResultSet</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateGraveyard(searchKey: ValidSearchKey, graveyard: ValidGraveyard, preparedStatement: PreparedStatement): int</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SqliteGraveyardRepository1287084334[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SqliteGraveyardRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   connection: Connection [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   graveyardMapper: SqliteGraveyardRowMapper [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   localeProvider: LocaleProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   logger: Logger [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   queryExecutor: SqliteGraveyardQueryExecutor [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ delete(searchKey: ValidSearchKey): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >+ get(searchKey: ValidSearchKey): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >+ getMatchingKeys(prefix: String): List&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getMatchingNames(prefix: String): List&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getNearestGraveyard(player: Player): Optional&lt;ValidGraveyard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getNearestGraveyards(player: Player): List&lt;ValidGraveyard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getUndiscoveredGraveyards(player: Player): Stream&lt;ValidGraveyard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getUndiscoveredKeys(sender: CommandSender): Set&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ save(graveyard: ValidGraveyard): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >+ saveAll(graveyards: Collection&lt;ValidGraveyard&gt;): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ update(graveyard: ValidGraveyard): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >+ update(oldSearchKey: ValidSearchKey, graveyard: ValidGraveyard): Graveyard</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SqliteGraveyardRowMapper1287084334[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SqliteGraveyardRowMapper</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ map(resultSet: ResultSet): Graveyard</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SqliteQueries1287084334[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SqliteQueries</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getQuery(query: String): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SqliteSchemaUpdaterFromV02051509663[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SqliteSchemaUpdaterFromV0</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   connection: Connection [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   discoveryRepository: DiscoveryRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   graveyardRepository: GraveyardRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   localeProvider: LocaleProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   plugin: Plugin [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ update()</TD></TR>
<TR><TD ALIGN="LEFT" >- updateDiscoveryTableSchema(connection: Connection, version: int)</TD></TR>
<TR><TD ALIGN="LEFT" >- updateGraveyardTableSchema(connection: Connection, version: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SqliteSchemaUpdaterNoOp2051509663[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SqliteSchemaUpdaterNoOp</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   localeProvider: LocaleProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   plugin: Plugin [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ update()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UnavailableWorld1429396403[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UnavailableWorld</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   uid: UUID [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ uid(): UUID</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ValidDiscovery836352235[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ValidDiscovery</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   playerUid: UUID [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   searchKey: ValidSearchKey [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ playerUid(): UUID</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchKey(): ValidSearchKey</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ValidDisplayName1488080184[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ValidDisplayName</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   string: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ toSearchKey(): ValidSearchKey</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ValidGraveyard46012934[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ValidGraveyard</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   attributes: Attributes [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   displayName: ValidDisplayName [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   location: ValidLocation [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ attributes(): Attributes</TD></TR>
<TR><TD ALIGN="LEFT" >+ displayName(): ValidDisplayName</TD></TR>
<TR><TD ALIGN="LEFT" >+ location(): ValidLocation</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchKey(): ValidSearchKey</TD></TR>
<TR><TD ALIGN="LEFT" >+ worldName(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ValidLocation977561318[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ValidLocation</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   pitch: float [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   world: ValidWorld [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   x: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   y: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   yaw: float [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   z: double [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ pitch(): float</TD></TR>
<TR><TD ALIGN="LEFT" >+ world(): ValidWorld</TD></TR>
<TR><TD ALIGN="LEFT" >+ x(): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ y(): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ yaw(): float</TD></TR>
<TR><TD ALIGN="LEFT" >+ z(): double</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ValidSearchKey1559188750[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ValidSearchKey</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   string: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ string(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
ListenerContextContainer82861217 -> SafetyManager1054240386[label="safetyManager
[0..1]"];
PlayerEventListener1298632657 -> ListenerContextContainer82861217[label="ctx
[0..1]"];
PlayerEventListener1298632657 -> SqliteConnectionProvider1287084334[arrowhead=none];
PlayerEventListener1298632657 -> SqliteGraveyardRepository1287084334[arrowhead=none];
PlayerEventListener1298632657 -> ValidGraveyard46012934[label="onPlayerRespawnHandler() -> displayName()"];
SafetyManager1054240386 -> ValidGraveyard46012934[label="put() -> attributes()"];
SqliteConnectionProvider1287084334 -> SqliteDiscoveryRepository1287084334[label="discoveryRepository
[0..1]"];
SqliteConnectionProvider1287084334 -> SqliteGraveyardRepository1287084334[label="graveyardRepository
[0..1]"];
SqliteConnectionProvider1287084334 -> SqliteSchemaUpdaterFromV02051509663[arrowhead=none];
SqliteConnectionProvider1287084334 -> SqliteSchemaUpdaterNoOp2051509663[arrowhead=none];
SqliteDiscoveryQueryExecutor1287084334 -> ValidSearchKey1559188750[label="insertDiscovery() -> string()"];
SqliteDiscoveryRepository1287084334 -> SqliteDiscoveryQueryExecutor1287084334[label="queryExecutor
[0..1]"];
SqliteDiscoveryRepository1287084334 -> SqliteDiscoveryRowMapper1287084334[label="discoveryMapper
[0..1]"];
SqliteDiscoveryRowMapper1287084334 -> InvalidDiscovery836352235[arrowhead=none];
SqliteDiscoveryRowMapper1287084334 -> ValidDiscovery836352235[arrowhead=none];
SqliteDiscoveryRowMapper1287084334 -> ValidGraveyard46012934[label="of() -> searchKey()", arrowhead=none];
SqliteGraveyardRepository1287084334 -> InvalidDisplayName1488080184[arrowhead=none];
SqliteGraveyardRepository1287084334 -> SqliteGraveyardQueryExecutor1287084334[label="queryExecutor
[0..1]"];
SqliteGraveyardRepository1287084334 -> SqliteGraveyardRowMapper1287084334[label="graveyardMapper
[0..1]"];
SqliteGraveyardRepository1287084334 -> ValidDisplayName1488080184[arrowhead=none];
SqliteSchemaUpdaterFromV02051509663 -> SqliteDiscoveryRepository1287084334[arrowhead=none];
ValidGraveyard46012934 -> AvailableWorld1429396403[arrowhead=none];
ValidGraveyard46012934 -> InvalidGraveyard46012934[arrowhead=none];
ValidGraveyard46012934 -> InvalidWorld1429396403[arrowhead=none];
ValidGraveyard46012934 -> UnavailableWorld1429396403[arrowhead=none];
ValidGraveyard46012934 -> ValidDisplayName1488080184[label="displayName
[0..1]"];
ValidGraveyard46012934 -> ValidLocation977561318[label="of() -> world()", arrowhead=none];
ValidLocation977561318 -> InvalidLocation977561318[arrowhead=none];
ValidSearchKey1559188750 -> InvalidSearchKey1559188750[arrowhead=none];
    
}
@enduml