@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "*attributes*",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "*Subcommand; *Key",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 2,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.winterhavenmc.savagegraveyards.core.PluginController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1655488073 { 
   	label=winterhavenmc
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_718573502 { 
   	label=savagegraveyards
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Bootstrap520637518[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Bootstrap</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   connectionProvider: ConnectionProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   pluginController: PluginController [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onDisable()</TD></TR>
<TR><TD ALIGN="LEFT" >+ onEnable()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CommandContextContainer82861217[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CommandContextContainer</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   datastore: ConnectionProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   discoveryObserver: DiscoveryObserver [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   messageBuilder: MessageBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   plugin: JavaPlugin [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   soundConfig: SoundConfiguration [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   worldManager: WorldManager [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ datastore(): ConnectionProvider</TD></TR>
<TR><TD ALIGN="LEFT" >+ discoveryObserver(): DiscoveryObserver</TD></TR>
<TR><TD ALIGN="LEFT" >+ messageBuilder(): MessageBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ plugin(): JavaPlugin</TD></TR>
<TR><TD ALIGN="LEFT" >+ soundConfig(): SoundConfiguration</TD></TR>
<TR><TD ALIGN="LEFT" >+ worldManager(): WorldManager</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CommandManager2027286168[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CommandManager</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ctx: CommandContextContainer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   subcommandRegistry: SubcommandRegistry [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- getSubcommandNameOrDefault(argsList: List&lt;String&gt;): String</TD></TR>
<TR><TD ALIGN="LEFT" >- getSubcommandOrFallback(sender: CommandSender, subcommandName: String): Optional&lt;Subcommand&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- hasPermission(sender: CommandSender): Predicate&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- matchesPrefix(prefix: String): Predicate&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- matchingNames(sender: CommandSender, matchString: String): List&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- notifyInvalidCommand(sender: CommandSender, subcommandName: String): Optional&lt;Subcommand&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCommand(sender: CommandSender, command: Command, label: String, args: String[]): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ onTabComplete(sender: CommandSender, command: Command, alias: String, args: String[]): List&lt;String&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

DiscoveryObserver1054240386[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DiscoveryObserver</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   datastore: ConnectionProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   discoveryTask: BukkitTask [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   messageBuilder: MessageBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   plugin: Plugin [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   soundConfig: SoundConfiguration [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ cancel()</TD></TR>
<TR><TD ALIGN="LEFT" >+ reload()</TD></TR>
<TR><TD ALIGN="LEFT" >+ run()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListenerContextContainer82861217[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListenerContextContainer</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   datastore: ConnectionProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   messageBuilder: MessageBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   plugin: JavaPlugin [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   safetyManager: SafetyManager [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   worldManager: WorldManager [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ datastore(): ConnectionProvider</TD></TR>
<TR><TD ALIGN="LEFT" >+ messageBuilder(): MessageBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ plugin(): JavaPlugin</TD></TR>
<TR><TD ALIGN="LEFT" >+ safetyManager(): SafetyManager</TD></TR>
<TR><TD ALIGN="LEFT" >+ worldManager(): WorldManager</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PlayerEventListener1298632657[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PlayerEventListener</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ctx: ListenerContextContainer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   deathTriggeredRespawn: Set&lt;UUID&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># onEntityTargetLivingEntity(event: EntityTargetLivingEntityEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onPlayerDeath(event: PlayerDeathEvent)</TD></TR>
<TR><TD ALIGN="LEFT" ># onPlayerRespawnHIGH(event: PlayerRespawnEvent)</TD></TR>
<TR><TD ALIGN="LEFT" ># onPlayerRespawnHIGHEST(event: PlayerRespawnEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >- onPlayerRespawnHandler(event: PlayerRespawnEvent)</TD></TR>
<TR><TD ALIGN="LEFT" ># onPlayerRespawnLOW(event: PlayerRespawnEvent)</TD></TR>
<TR><TD ALIGN="LEFT" ># onPlayerRespawnLOWEST(event: PlayerRespawnEvent)</TD></TR>
<TR><TD ALIGN="LEFT" ># onPlayerRespawnNORMAL(event: PlayerRespawnEvent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SafetyManager1054240386[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SafetyManager</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   messageBuilder: MessageBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   plugin: Plugin [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   safetyCooldownMap: Map&lt;UUID, BukkitRunnable&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ isProtected(player: Player): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ put(player: Player, graveyard: ValidGraveyard)</TD></TR>
<TR><TD ALIGN="LEFT" >+ remove(player: Player)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PluginController1876166622[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PluginController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   commandManager: CommandManager [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   datastore: ConnectionProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   discoveryObserver: DiscoveryObserver [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   messageBuilder: MessageBuilder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   playerEventListener: PlayerEventListener [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   safetyManager: SafetyManager [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   soundConfig: SoundConfiguration [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   worldManager: WorldManager [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ shutDown()</TD></TR>
<TR><TD ALIGN="LEFT" >+ startUp(plugin: JavaPlugin, connectionProvider: ConnectionProvider)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];


SqliteConnectionProvider1287084334[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SqliteConnectionProvider</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   connection: Connection [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dataFilePath: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   discoveryRepository: SqliteDiscoveryRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   graveyardRepository: SqliteGraveyardRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   initialized: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   localeProvider: LocaleProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   plugin: Plugin [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ close()</TD></TR>
<TR><TD ALIGN="LEFT" >+ connect(): ConnectionProvider</TD></TR>
<TR><TD ALIGN="LEFT" >- createDiscoveryTable(connection: Connection, localeProvider: LocaleProvider)</TD></TR>
<TR><TD ALIGN="LEFT" >- createGraveyardTable(connection: Connection, localeProvider: LocaleProvider)</TD></TR>
<TR><TD ALIGN="LEFT" >+ discoveries(): DiscoveryRepository</TD></TR>
<TR><TD ALIGN="LEFT" >- enableForeignKeys(connection: Connection, localeProvider: LocaleProvider)</TD></TR>
<TR><TD ALIGN="LEFT" >+ graveyards(): GraveyardRepository</TD></TR>
<TR><TD ALIGN="LEFT" >- initialize()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SqliteGraveyardRepository1287084334[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SqliteGraveyardRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   connection: Connection [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   graveyardMapper: SqliteGraveyardRowMapper [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   localeProvider: LocaleProvider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   logger: Logger [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   queryExecutor: SqliteGraveyardQueryExecutor [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ delete(searchKey: ValidSearchKey): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >+ get(searchKey: ValidSearchKey): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >+ getMatchingKeys(prefix: String): List&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getMatchingNames(prefix: String): List&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getNearestGraveyard(player: Player): Optional&lt;ValidGraveyard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getNearestGraveyards(player: Player): List&lt;ValidGraveyard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getUndiscoveredGraveyards(player: Player): Stream&lt;ValidGraveyard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getUndiscoveredKeys(sender: CommandSender): Set&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ save(graveyard: ValidGraveyard): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >+ saveAll(graveyards: Collection&lt;ValidGraveyard&gt;): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ update(graveyard: ValidGraveyard): Graveyard</TD></TR>
<TR><TD ALIGN="LEFT" >+ update(oldSearchKey: ValidSearchKey, graveyard: ValidGraveyard): Graveyard</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SubcommandRegistry2027286168[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SubcommandRegistry</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   aliasMap: Map&lt;String, String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >#   subcommandMap: Map&lt;String, Subcommand&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># getSubcommand(name: String): Optional&lt;Subcommand&gt;</TD></TR>
<TR><TD ALIGN="LEFT" ># register(subcommand: Subcommand)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ValidGraveyard46012934[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ValidGraveyard</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   attributes: Attributes [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   displayName: ValidDisplayName [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   location: ValidLocation [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ attributes(): Attributes</TD></TR>
<TR><TD ALIGN="LEFT" >+ displayName(): ValidDisplayName</TD></TR>
<TR><TD ALIGN="LEFT" >+ location(): ValidLocation</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchKey(): ValidSearchKey</TD></TR>
<TR><TD ALIGN="LEFT" >+ worldName(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Bootstrap520637518 -> PluginController1876166622[label="pluginController
[0..1]"];
CommandManager2027286168 -> CommandContextContainer82861217[label="ctx
[0..1]"];
CommandManager2027286168 -> SubcommandRegistry2027286168[label="subcommandRegistry
[0..1]"];
PlayerEventListener1298632657 -> ListenerContextContainer82861217[label="ctx
[0..1]"];
PlayerEventListener1298632657 -> SqliteConnectionProvider1287084334[arrowhead=none];
PlayerEventListener1298632657 -> SqliteGraveyardRepository1287084334[arrowhead=none];
PlayerEventListener1298632657 -> ValidGraveyard46012934[label="onPlayerRespawnHandler() -> displayName()"];
PluginController1876166622 -> CommandManager2027286168[label="commandManager
[0..1]"];
PluginController1876166622 -> DiscoveryObserver1054240386[label="discoveryObserver
[0..1]"];
PluginController1876166622 -> PlayerEventListener1298632657[label="playerEventListener
[0..1]"];
PluginController1876166622 -> SafetyManager1054240386[label="safetyManager
[0..1]"];
    
}
@enduml