@startuml

' === GLOBAL STYLING ===
skinparam backgroundColor #f9f9f9
skinparam shadowing true
skinparam roundCorner 15
skinparam ArrowColor #444444
skinparam ArrowThickness 1.2
skinparam ArrowFontSize 11
skinparam packageTitleFontSize 14
skinparam classFontName "Helvetica"
skinparam classAttributeIconSize 0
skinparam class {
  BackgroundColor white
  BorderColor #888888
}
skinparam class {
  BackgroundColor<<entity>> #cfefff
    BackgroundColor<<entity-valid>> #e6ffe6
  BackgroundColor<<entity-invalid>> #ffe6e6
}

package SavageGraveyards
{
    package models
    {
        interface SearchKey <<Entity>>
        {
            + of(args: List&lt;String&gt;): SearchKey
            + of(string: String): SearchKey
            + string(): String
            + toDisplayName(): DisplayName
        }

        class ValidSearchKey <<Entity-valid>>
        {
            - string: String
            --
            + string(): String
        }

        class InvalidSearchKey <<Entity-invalid>>
        {
            - reason: SearchKeyFailReason
            - string: String
            --
            + reason(): SearchKeyFailReason
            + string(): String
        }
    }
}
SearchKey <-- ValidSearchKey
SearchKey <-- InvalidSearchKey

@enduml
